[build]
functions = "netlify/functions"

[functions]
node_bundler = "esbuild"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[plugins]]
package = "@netlify/plugin-functions-install-core"
